apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: argocd-route

  labels:
    wan-mode: 'public'
    lan-mode: 'private'

spec:
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      namespace: core-prod
      name: main-gw

  hostnames:
    - 'argo.writemy.codes'

  rules:
    - backendRefs:
        - name: argocd-server
          port: 443

      timeouts:
        request: 300s
        backendRequest: 300s