apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: core-backplane-network-ipam
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - cluster: dc1-k3s-node1
            url: https://kubernetes.default.svc

  syncPolicy:
    preserveResourcesOnDeletion: true

  template:
    metadata:
      name: '{{cluster}}-network-ipam'

      annotations:
        argocd.argoproj.io/manifest-generate-paths: .

    spec:
      project: core

      source:
        path: Network/IPAM
        repoURL: https://github.com/K-FOSS/node1-k3s.dc1.resolvemy.host.git
        targetRevision: HEAD
        plugin:
          name: argocd-lovely-plugin
          env:
            - name: ARGOCD_APP_NAME
              value: 'netbox-ipam'
        #     - name: LOVELY_HELM_MERGE
        #       value: |-
        #         coredns:
        #           affinity:
        #             podAntiAffinity:
        #               preferredDuringSchedulingIgnoredDuringExecution:
        #                 - weight: 100
        #                   podAffinityTerm:
        #                     labelSelector:
        #                       matchExpressions:
        #                         - key: app.kubernetes.io/instance
        #                           operator: In
        #                           values:
        #                             - '{{cluster}}-rdns-lab'
        #                     topologyKey: kubernetes.io/hostname

        #           serviceType: LoadBalancer
        #           service:
        #             annotations:
        #               purelb.io/service-group: anycast
        #             name: test-dns-rdns-core
        #             externalTrafficPolicy: Local
        #             loadBalancerIP: '{{loadBalancerIP}}'



      destination:
        server: '{{url}}'
        namespace: core-prod
