apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyProxy
metadata:
  name: envoy-config

spec:
  telemetry:
    tracing:
      # sample 1% of requests
      samplingRate: 1
      provider:
        host: tempo-core-tempo.core-prod.svc.cluster.local
        port: 4317
        type: OpenTelemetry

  mergeGateways: false
  provider:
    type: Kubernetes
    kubernetes:
      envoyDeployment:
        replicas: 2



      #useListenerPortAsContainerPort: true

      envoyService:
        type: LoadBalancer