apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyProxy
metadata:
  name: envoy-config

spec:
  telemetry:
    tracing:
      # sample 1% of requests
      samplingRate: 1
      provider:
        host: tempo-core-tempo.core-prod.svc.cluster.local
        port: 4317
        type: OpenTelemetry

  mergeGateways: false
  provider:
    type: Kubernetes
    kubernetes:
      envoyService:
        type: LoadBalancer
        externalTrafficPolicy: Local
      envoyDeployment:
        replicas: 2
          
        container:
          resources:
            requests:
              cpu: 150m
              memory: 640Mi
            limits:
              cpu: 500m
              memory: 1Gi

        pod:
          labels:
            logs: loki-myloginspace



      #useListenerPortAsContainerPort: true

      envoyService:
        type: LoadBalancer