apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyProxy
metadata:
  name: envoy-config

spec:
  telemetry:
    tracing:
      # sample 100% of requests
      samplingRate: 100
      provider:
        host: tempo-core-tempo.core-prod.svc.cluster.local
        port: 4317
        type: OpenTelemetry

  mergeGateways: false
  provider:
    type: Kubernetes
    kubernetes:
      envoyDaemonSet:
        name: main-gw

      #useListenerPortAsContainerPort: true

      envoyService:
        type: LoadBalancer