apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyProxy
metadata:
  name: envoy-config

spec:
  telemetry:
    accessLog:
      disable: false
      settings:
        - format:
            type: JSON
            json:
              status: "%RESPONSE_CODE%"
              message: "%LOCAL_REPLY_BODY%"

          sinks:
            - type: OpenTelemetry
              openTelemetry:
                backendRefs:
                  - group: ''
                    kind: Service
                    name: dc1-k3s-node1-collectors-alloy
                    namespace: core-prod
                    port: 4317

                resources:
                  k8s.cluster.name: "dc1-k3s"
    tracing:
      # sample 1% of requests
      samplingRate: 1
      provider:
        backendRefs:
          - group: ''
            kind: Service
            name: dc1-k3s-node1-collectors-alloy
            namespace: core-prod
            port: 4317
            weight: 1

        type: OpenTelemetry

  mergeGateways: false
  provider:
    type: Kubernetes
    kubernetes:
      envoyService:
        type: LoadBalancer
        externalTrafficPolicy: Local
      envoyDeployment:
        replicas: 2
          
        container:
          resources:
            requests:
              cpu: 150m
              memory: 640Mi
            limits:
              cpu: 500m
              memory: 1Gi

        pod:
          labels:
            logs: loki-myloginspace



      #useListenerPortAsContainerPort: true

      envoyService:
        type: LoadBalancer