apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: hubble-ui
spec:
  issuerRef:
    name: kjdev-cluster
    kind: ClusterIssuer

  secretName: hubble-ui-certs

  commonName: 'ui.hubble.k3s.dc1.resolvemy.host'
  dnsNames:
    - 'ui.hubble.k3s.dc1.resolvemy.host'

