apiVersion: purelb.io/v1
kind: ServiceGroup
metadata:
  name: main-public
spec:
  local:
    v4pools:
      - subnet: 66.165.222.96/27
        pool: 66.165.222.102/32
        aggregation: default
---
apiVersion: purelb.io/v1
kind: ServiceGroup
metadata:
  name: anycast
spec:
  local:
    v4pools:
      - subnet: 10.1.1.0/24
        pool: 10.1.1.0/24
        aggregation: default
    
      - subnet: 66.165.222.96/27
        pool: 66.165.222.100/32
        aggregation: default

      # ns1.resolvemy.host
      - subnet: 66.165.222.96/27
        pool: 66.165.222.105/32
        aggregation: default

      - subnet: 66.165.222.96/27
        pool: 66.165.222.110-66.165.222.127
        aggregation: default
---