apiVersion: v1
kind: ConfigMap
metadata:
  name: sriovdp-config
  namespace: kube-system
data:
  config.json: |
    {
      "resourceList": [
        {
          "resourceName": "intel_xxv710_vfio",
          "resourcePrefix": "intel.com",
          "selectors": [
            {
              "vendors": ["8086"],
              "devices": ["154c"],
              "drivers": ["vfio-pci"],
              "pfNames": ["enp5s0f0np0", "enp5s0f1np1"]
            }
          ]
        },
        {
          "resourceName": "intel_xxv710",
          "resourcePrefix": "intel.com",
          "selectors": [
            {
              "vendors": ["8086"],
              "devices": ["154c"],
              "drivers": ["iavf"],
              "pfNames": ["enp5s0f0np0", "enp5s0f1np1"]
            }
          ]
        }
      ]
    }